### ISSUE TITLE
Legacy media notification style 

### ISSUE THREAD

**Issue by vlzuykov** [Podcast-Republic/PRApp#431]
Several recent updates of the app cannot display modern Android media notifications. On Android 12, the app only displays legacy media notifications.

**Comment by gemiren** [comment]
The legacy option was incorrectly enabled if you turned on to use default chapter title in the last couple of beta versions. This bug has been fixed in today's update. Please update your app to the latest version. After you have the latest app version installed please go to app settings > Notifications to turn off the legacy notification option. That option will now stay in the off state. Thanks.

**Comment by vlzuykov** [comment]
I upgraded to 25.5.16R. Then I disabled this option. And I still can't see anything but the legacy media notification.
![Screenshot_2024-05-17-08-06-33-467-edit_com.itunestoppodcastplayer.app.jpg](https://github.com/Podcast-Republic/PRApp/assets/2944126/455bd17f-b605-4ebb-a5ee-6a564953e6ed)

**Comment by gemiren** [comment]
Have you tried rebooting? Thanks.

**Comment by vlzuykov** [comment]
Yes, it did not affect the issue at all

**Comment by gemiren** [comment]
That's really weird. Can you go to the app Settings> About to use 'Report a bug' button to send the app log? Thanks!

**Comment by vlzuykov** [comment]
It was fixed in 24.5.17R. Thanks.
